// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type UserDetailRequest struct {
	Id int `json:"id"`
}

type UserDetailReply struct {
	UserName string `json:"username"`
	Email    string `json:"email"`
}

type EmailSendRequest struct {
	Email string `json:"email"`
}

type EmailSendReply struct {
	Message string `json:"message"`
}
